# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-11 06:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0006_auto_20180111_0625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantlocation',
            name='my_date_field',
        ),
    ]
